# Generated by Django 5.1.2 on 2024-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='users',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rua',
        ),
        migrations.AddField(
            model_name='users',
            name='lutador',
            field=models.BooleanField(default=False),
        ),
    ]
