# Generated by Django 5.1.2 on 2024-11-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lutadores',
            name='idade',
        ),
        migrations.AddField(
            model_name='lutadores',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
