# Generated by Django 5.1.2 on 2024-11-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutadores', '0003_livros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livros',
        ),
        migrations.AddField(
            model_name='lutadores',
            name='contato',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='lutadores',
            name='experiencia',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='lutadores',
            name='peso',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='lutadores',
            name='tecnico',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='lutadores',
            name='equipe',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='lutadores',
            name='nome',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
