# Generated by Django 5.1.2 on 2024-11-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutadores', '0006_rename_experiencia_lutadores_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_luta', models.DateField()),
                ('hora_luta', models.TimeField()),
                ('local_luta', models.CharField(max_length=100)),
                ('lutador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luta_lutador1', to='lutadores.lutadores')),
                ('lutador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luta_lutador2', to='lutadores.lutadores')),
            ],
        ),
    ]
