# Generated by Django 5.1.2 on 2024-11-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lutadores', '0007_lutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutas',
            name='dia_luta',
            field=models.CharField(choices=[('Dia 1', 'Dia 1'), ('Dia 2', 'Dia 2')], max_length=5),
        ),
    ]
