# Generated by Django 5.1.2 on 2024-11-24 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('hora_pagamento', models.TimeField(default=django.utils.timezone.now)),
                ('status_pagamento', models.CharField(choices=[('Aguardando Pagamento', 'Aguardando Pagamento'), ('Pagamento Aprovado', 'Pagamento Aprovado'), ('Pagamento Expirado', 'Pagamento Expirado')], default='Aguardando Pagamento', max_length=20)),
                ('tipo_ingresso', models.CharField(choices=[('Dia 1', 'Dia 1'), ('Dia 1 VIP', 'Dia 1 VIP'), ('Dia 2', 'Dia 2'), ('Dia 2 VIP', 'Dia 2 VIP'), ('Lutador', 'Lutador')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
